### ISSUE TITLE
Not on hackage ?

### ISSUE THREAD

**Issue by SRAZKVT** [isaacvando/cooklang-hs#2]
Is there any plan of getting this parser on hackage for usage by other programs / libraries around cooklang ? Or should people who want to use a cooklang parser just take the parser and embed it into their package ? I'm making a small haskell utility for myself and i'd like to know how i should handle this project.

**Comment by isaacvando** [comment]
I just haven't gotten around to publishing it. I can do that sometime this week, I will let you know when I release it!

**Comment by SRAZKVT** [comment]
Hey, any idea when that might be ?

**Comment by isaacvando** [comment]
I was waiting on being added to the Hackage uploader group (turns out I missed the email that I had been added). I will take a look at getting the package uploaded now.

**Comment by isaacvando** [comment]
@SRAZKVT Alright, the package is published! https://hackage.haskell.org/package/cooklang-hs

Let me know if you run into issues.
